services:
  backend:
    build:
      context: ./src/backend
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
    volumes: 
      - ./src/backend:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "4000:4000"

  frontend:
    volumes: 
      - ./src/frontend:/app
    env_file:
      - .env.dev
    ports: 
      - "3000:3000"
  
  db:
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - ./src/db/dev:/var/lib/postgresql/data