services:
  backend:
    build: 
      context: ./src/backend
    ports:
      - "4000:4000"
    depends_on:
      - db
  
  frontend:
    build: 
      context: ./src/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13-alpine
    volumes:
      - ./src/db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"