services:
  backend:
    build:
      context: ./backend
      args:
        NODE_ENV: test
    environment:
      - NODE_ENV=test
    ports:
      - "4000:4000"
    command: npm run test
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    env_file: 
      - .env.test
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  db:
    env_file:
      - .env.test
    ports:
      - "5432:5432"
    volumes:
      - ./db/test:/var/lib/postgresql/data