services:
  backend:
    build: 
      context: ./backend
    ports:
      - "${PORT:-4000}:4000"
    depends_on:
      - db
  
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:${PORT:-4000}

  db:
    image: postgres:13-alpine
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"