services:
  backend:
    env_file: 
      - .env.dev
    volumes:
      - ./backend:/app
    command: npm run dev
    ports:
      - "${PORT:-4000}:4000"

  frontend:
    env_file:
      - .env.dev
    volumes:
      - ./frontend:/app
    ports: "${FRONTEND_PORT:-3000}:3000"
    build: ./frontend
  
  db:
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data