services:
  backend:
    build:
      context: ./src/backend
    volumes: 
      - /src/backend
    environment:
      NODE_ENV: test
    ports:
      - "4000:4000"
    command: ./run_tests.sh
    depends_on:
      - db

  frontend:
    build:
      context: ./src/frontend
    env_file: 
      - .env.test
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  db:
    env_file:
      - .env.test
    ports:
      - "5432:5432"
    volumes:
      - ./src/db/test:/var/lib/postgresql/data