services:
  backend:
    env_file:
      - .env.test
    command: npm run test
    ports:
      - "${PORT:-4000}:4000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  db:
    env_file:
      - .env.test
    ports:
      - "5432:5432"
    volumes:
      - ./test-db-data:/var/lib/postgresql/data