services:
  backend:
    build:
      context: ./backend
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    ports:
      - "80:4000"
    command: npm start
    depends_on:
      - db
  
  frontend:
    context: ./frontend
    env_file:
      - .env.prod
    ports:
      - "443:3000"
  
  db:
    image: postgres:13-alpine
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    volumes:
      - ./db/prod:/var/lib/postgresql/data
