services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env.prod
    ports:
      - "80:4000"
    depends_on:
      - db
  
  frontend:
    build:
      context: ./frontend
    env_file:
      - .env.prod
    ports:
      - "443:3000"
  
  db:
    image: postgres:13-alpine
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    volumes:
      - ./genericWebApp_prod:/var/lib/postgresql/data
