services:
  backend:
    volumes: 
      - ./backend:/app
    env_file: 
      - .env.dev
    command: npm run dev
    ports:
      - "4000:4000"

  frontend:
    volumes: 
      - ./frontend:/src/app
    env_file:
      - .env.dev
    ports: 
      - "3000:3000"
  
  db:
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - ./db/dev:/var/lib/postgresql/data