services:
  backend:
    env_file: 
      - .env.dev
    command: npm run dev
    ports:
      - "4000:4000"

  frontend:
    env_file:
      - .env.dev
    ports: 
      - "3000:3000"
  
  db:
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - ./db/dev:/var/lib/postgresql/data